# AI-assisted scaffold: review & refactor before commit
version: "3.9"

services:
  mongo:
    image: mongo:7
    container_name: notes-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  backend:
    build: ./backend
    container_name: notes-backend
    env_file: ./backend/.env
    depends_on:
      - mongo
    ports:
      - "8000:8000"
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000

  frontend:
    build: ./frontend
    container_name: notes-frontend
    env_file: ./frontend/.env
    depends_on:
      - backend
    ports:
      - "3000:3000"
    command: npm run dev

volumes:
  mongo_data: